### ISSUE TITLE
Subscribed link not working from repo notifications

### ISSUE THREAD

**Issue by marpo60** [marpo60/github-subscribed#2]
When visiting a notifications page for a particular repo [example](https://github.com/mvdwg/ember-cli-diff/notifications) the 'Subscribed' link is not working :(

Thanks @san650 for the report.

**Comment by marpo60** [comment]
Fixed with https://github.com/marpo60/github-subscribed/commit/a03b1f046842df94bd241f8567be42e6110fdc9e

**Comment by marpo60** [comment]
Test

**Comment by marpo60** [comment]
Abc

**Comment by san650** [comment]
Thanks @marpo60!!
