### ISSUE TITLE
List does not shown subscribed entries

### ISSUE THREAD

**Issue by dmetzler1988** [marpo60/github-subscribed#3]
Chrome Version 59.0.3071.115
Plugin Version 1.1.1

If i unsubscribe and subscribe an issue, then it would not be shown in the list.

Also if i open a new issue - i am automatically be subscribed, but not shown in the list.

So the list does not work for me.

**Comment by dmetzler1988** [comment]
Additional:
After i created this issue, i have one subscribed element in the list - this one.

**Comment by marpo60** [comment]
Thanks for reporting this will take a look.

**Comment by marpo60** [comment]
@dmetzler1988  Is this still happening?

**Comment by dmetzler1988** [comment]
yes, same problem with newest chrome version.

I installed it on a new pc - and it doesn't show any subscribed elements (Subscribed 0).

Maybe this is the reason (that the subscribed elements will be saved to the local storage of plugin and not read the subscribed element from currently logged in user)?

**Comment by marpo60** [comment]
Yes, thats the case. Currently the extensions saves you subscriptions in local storage

**Comment by marpo60** [comment]
Closing it for now

Can you test again with `v1.2.1` and re open if the issue persists? Thanks
