### ISSUE TITLE
Removed access - always subscribed

### ISSUE THREAD

**Issue by dmetzler1988** [marpo60/github-subscribed#4]
Chrome Version 67.0.3396.87
Plugin Version 1.1.1

I was removed from a private repository so i don't have access to it. Now i can't unsubscribe me from the issues. But this issues are shown in the subscribed list.

I am not sure if you can do there anything. 
- Maybe ignore subscriptions from  repositories with no access. 
- Or add a unsubscribe button to the list?
- Or add a filter option to see all or only this with access.

**Comment by marpo60** [comment]
Thanks for reporting this issue!

Probably option 2 is the easiest one to implement. 

Will work on it, and let you know once is pushed.

**Comment by marpo60** [comment]
Hi

I added the ability to delete the subscription from the subscriptions page

Released in `v1.2.1`

Cheers!
