### ISSUE TITLE
Does this work for firefox?

### ISSUE THREAD

**Issue by Compro-Prasad** [marpo60/github-subscribed#5]

**Comment by marpo60** [comment]
Not yet... :(

But I will leave this ticket open because is my intention to make it available in firefox also.

**Comment by icefed** [comment]
Hi, I Have tested in firefox(https://www.extensiontest.com/), and it have no incompatibilities.

**Comment by hidnasio** [comment]
I've tested it in Firefox Developer Edition v65 and is working fine.

**Comment by Darkilen** [comment]
I confirm, it's working fine on Firefox developer Edition v65.
Could you publish it to https://addons.mozilla.org ?

**Comment by marpo60** [comment]
Sounds good, thanks all.
I will publish it this week :)

**Comment by Darkilen** [comment]
Any news ?

**Comment by marpo60** [comment]
Hi all,

I publish it to Firefox Add-ons:
https://addons.mozilla.org/en-US/firefox/addon/github-subscribed/

Sorry for the delay.

**Comment by icefed** [comment]
Hi, all
Good news, the Subscription List feature is out. https://github.com/notifications/subscriptions
https://github.com/isaacs/github/issues/283#issuecomment-470853982
